services:
  nn:
    environment:
      - AUTOENCODER_THRESHOLD=${AUTOENCODER_THRESHOLD}
    build:
      dockerfile: ${PWD}/dockerfiles/nn.dockerfile
    volumes:
      - ${PWD}/models:/models
    ports:
      - ${PORT_NN_SERVICE}:8008
    restart: always
  
  tg_bot:
    environment:
      - PORT_NN_SERVICE=${PORT_NN_SERVICE}
      - BOT_KEY=${BOT_KEY}
    build:
      dockerfile: ${PWD}/dockerfiles/tg_bot.dockerfile
    restart: always
    depends_on:
      nn:
        condition: service_completed_successfully

